const ActionTypes = {
  homeSlideImg: "homeSlideImg",
  homeIntro: "homeIntro",
  projectCat: "projectCat",
  bookAllCat: "bookAllCat",
  onlineMasajidForms: "onlineMasajidForms",
  onlineQuranPakForms: 'onlineQuranPakForms',
  bookAllSpe: "bookAllSpe",
  SaylaniNewsGet: "SaylaniNewsGet",
  fieldEmpty: "fieldEmpty",
  roPlantBranchGet: "roPlantBranchGet",
  RoPlantEstiCostGet: "RoPlantEstiCostGet",
  RoPlantLocationGet: "RoPlantLocationGet",
  JobBankHuntGet: "JobBankHuntGet",
  jobBankFormGet: "jobBankFormGet",
  DonaListGet: "DonaListGet",
  QuranAppAndroidGet: "QuranAppAndroidGet",
  QuranAppIosGet: "QuranAppIosGet",
  smitNotificationGet: "smitNotificationGet",
  mediaGet: "mediaGet",
  smitFacultyGet: "smitFacultyGet",
  smitFacultyCourseGet: 'smitFacultyCourseGet',
  SmitCollaborationGet: "SmitCollaborationGet",
  smitWorkshopGet: "smitWorkshopGet",
  SmitCounGet: "SmitCounGet",
  patientTreatedGet: "patientTreatedGet",
  SmitsucessGet: "SmitsucessGet",
  smitCoursesGet: 'smitCoursesGet',
  schoolCampusGet: 'schoolCampusGet',
  schoolCountGet: 'schoolCountGet',
  schoolTeacherGet: 'schoolTeacherGet',
  schoolFeatureGet: 'schoolFeatureGet',
  medicalServiceAdd: 'medicalServiceAdd',
  benificiariesCountGet: 'benificiariesCountGet',
  opdNameGet: "opdNameGet",
  opdListGet: "opdListGet",
  stdData:'stdData',
  SaylaniHomeNewsGet:'SaylaniHomeNewsGet'
};

export default ActionTypes;
